version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./app/src:/var/www/html
    depends_on:
      - app

  app:
    build: ./app
    volumes:
      - ./app/src:/var/www/html
      - ./tmp:/var/www/uploads
